/*
 *  Copyright 2009 Mario.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */

/*
 * MainFrameEx.java
 *
 * Created on 05.12.2009, 20:10:56
 */

package net.sourceforge.jeuclid.app.mathviewer;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.File;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.KeyStroke;
import javax.swing.ScrollPaneConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import javax.swing.text.BadLocationException;
import net.sourceforge.jeuclid.MathMLSerializer;
import net.sourceforge.jeuclid.context.LayoutContextImpl;
import net.sourceforge.jeuclid.context.Parameter;
import net.sourceforge.jeuclid.swing.JMathComponent;

import org.apache.batik.util.gui.xmleditor.XMLContext;
import org.apache.batik.util.gui.xmleditor.XMLEditorKit;
import org.apache.batik.util.gui.xmleditor.XMLTextEditor;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.w3c.dom.Document;


/**
 *
 * @author Mario
 */
public class MainFrameEx extends javax.swing.JFrame {
    private static final int DEFAULT_HEIGHT = 400;

    private static final int DEFAULT_WIDTH = 700;
    
    private static final FileIO FILEIO = FileIO.getInstance();
    private static final long serialVersionUID = 1L;
    private static final float FONT_SIZE_MULTIPLICATOR = 1.20f;


    private XMLTextEditor xmlEditor;
    private AboutDialog aboutDialog;
    private JMathComponent mathComponent;

    private static final Log LOGGER = LogFactory.getLog(MainFrameEx.class);
    
    /** Creates new form MainFrameEx */
    public MainFrameEx() {
        initComponents();
        this.setSize(MainFrameEx.DEFAULT_WIDTH, MainFrameEx.DEFAULT_HEIGHT);
        this.setTitle(Messages.getString("MathViewer.windowTitle")); //$NON-NLS-1$
        //this.jContentPane.add(this.splitPane, BorderLayout.CENTER);
        this.setLocationByPlatform(true);
        this.updateFromTextArea();
    }

        /*private void updateFromTextArea() {
        try {
            this.getMathComponent().setContent(this.getXMLEditor().getText());
            this.xmlEditor.setBackground(Color.getHSBColor(0.3f, 0.2f, 1.0f));
            // CHECKSTYLE:OFF
            // in this case, we want to explicitly provide catch-all error
            // handling.
        } catch (final RuntimeException e) {
            // CHECKSTYLE:ON
            this.xmlEditor.setBackground(Color.getHSBColor(0f, 0.2f, 1.0f));
        }
    }*/


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contextMenu = new javax.swing.JPopupMenu();
        insertMenu = new javax.swing.JMenu();
        insertTableMenuItem = new javax.swing.JMenuItem();
        insertPolynomMenuItem = new javax.swing.JMenuItem();
        logicsMenu = new javax.swing.JMenu();
        orMenuItem = new javax.swing.JMenuItem();
        andMenuItem = new javax.swing.JMenuItem();
        notMenuItem = new javax.swing.JMenuItem();
        greekMenu = new javax.swing.JMenu();
        alphaMenuItem = new javax.swing.JMenuItem();
        betaMenuItem = new javax.swing.JMenuItem();
        gammaMenuItem = new javax.swing.JMenuItem();
        deltaMenuItem = new javax.swing.JMenuItem();
        epsilonMenuItem = new javax.swing.JMenuItem();
        zetaMenuItem = new javax.swing.JMenuItem();
        omegaMenuItem = new javax.swing.JMenuItem();
        combinatoricsMenu = new javax.swing.JMenu();
        overMenuItem = new javax.swing.JMenuItem();
        refreshCMenuItem = new javax.swing.JMenuItem();
        jContentPane = new javax.swing.JPanel();
        splitPane = new javax.swing.JSplitPane();
        scrollPane2 = new javax.swing.JScrollPane();
        scrollPane = new javax.swing.JScrollPane();
        jMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        exportMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        formattedCopyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        unformattedCopyMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        aliasMenuItem = new javax.swing.JCheckBoxMenuItem();
        smallerMenuItem = new javax.swing.JMenuItem();
        biggerMenuItem = new javax.swing.JMenuItem();
        debugMenuItem = new javax.swing.JCheckBoxMenuItem();
        refreshMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        insertMenu.setText("Einfuegen");
        insertMenu.setActionCommand("Einfuegen");

        insertTableMenuItem.setText("Tabelle...");
        insertTableMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertTableMenuItemActionPerformed(evt);
            }
        });
        insertMenu.add(insertTableMenuItem);

        insertPolynomMenuItem.setText("Polynom...");
        insertPolynomMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertPolynomMenuItemActionPerformed(evt);
            }
        });
        insertMenu.add(insertPolynomMenuItem);

        logicsMenu.setText("Logik");

        orMenuItem.setText("OR");
        orMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orMenuItemActionPerformed(evt);
            }
        });
        logicsMenu.add(orMenuItem);

        andMenuItem.setText("AND");
        andMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andMenuItemActionPerformed(evt);
            }
        });
        logicsMenu.add(andMenuItem);

        notMenuItem.setText("NOT");
        notMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notMenuItemActionPerformed(evt);
            }
        });
        logicsMenu.add(notMenuItem);

        insertMenu.add(logicsMenu);

        greekMenu.setText("Griechisch");

        alphaMenuItem.setText("Alpha");
        alphaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alphaMenuItemActionPerformed(evt);
            }
        });
        greekMenu.add(alphaMenuItem);

        betaMenuItem.setText("Beta");
        betaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betaMenuItemActionPerformed(evt);
            }
        });
        greekMenu.add(betaMenuItem);

        gammaMenuItem.setText("Gamma");
        gammaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gammaMenuItemActionPerformed(evt);
            }
        });
        greekMenu.add(gammaMenuItem);

        deltaMenuItem.setText("Delta");
        deltaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deltaMenuItemActionPerformed(evt);
            }
        });
        greekMenu.add(deltaMenuItem);

        epsilonMenuItem.setText("Epsilon");
        epsilonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epsilonMenuItemActionPerformed(evt);
            }
        });
        greekMenu.add(epsilonMenuItem);

        zetaMenuItem.setText("Zeta");
        zetaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zetaMenuItemActionPerformed(evt);
            }
        });
        greekMenu.add(zetaMenuItem);

        omegaMenuItem.setText("Omega");
        omegaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                omegaMenuItemActionPerformed(evt);
            }
        });
        greekMenu.add(omegaMenuItem);

        insertMenu.add(greekMenu);

        combinatoricsMenu.setText("Kombinatorik");

        overMenuItem.setText("n über k");
        combinatoricsMenu.add(overMenuItem);

        insertMenu.add(combinatoricsMenu);

        contextMenu.add(insertMenu);

        refreshCMenuItem.setText("Aktuallisieren");
        refreshCMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshCMenuItemActionPerformed(evt);
            }
        });
        contextMenu.add(refreshCMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frameMain"); // NOI18N

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setResizeWeight(1.0);
        splitPane.setOneTouchExpandable(true);

        scrollPane2.setMinimumSize(new java.awt.Dimension(50, 50));
        splitPane.setRightComponent(scrollPane2);
        scrollPane2.setViewportView(this.getXMLEditor());

        if (MathViewer.OSX) {
            scrollPane2.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
            scrollPane2.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        }
        splitPane.setLeftComponent(scrollPane);
        scrollPane.setViewportView(this.getMathComponent());

        if (MathViewer.OSX) {
            scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
            scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        }

        javax.swing.GroupLayout jContentPaneLayout = new javax.swing.GroupLayout(jContentPane);
        jContentPane.setLayout(jContentPaneLayout);
        jContentPaneLayout.setHorizontalGroup(
            jContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        jContentPaneLayout.setVerticalGroup(
            jContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        getContentPane().add(jContentPane, java.awt.BorderLayout.CENTER);

        fileMenu.setText(Messages.getString("MathViewer.FileMenu"));

        exitMenuItem.setText(Messages.getString("MathViewer.exit"));
        exitMenuItem.setAccelerator(KeyStroke.getKeyStroke(
            KeyEvent.VK_Q, Toolkit.getDefaultToolkit()
            .getMenuShortcutKeyMask(), true));
    exitMenuItem.addActionListener(new ActionListener() {
        public void actionPerformed(final ActionEvent e) {
            System.exit(0);
        }
    });
    fileMenu.add(exitMenuItem);

    exportMenuItem.setText(Messages
        .getString("MathViewer.export"));
    fileMenu.add(exportMenuItem);
    exportMenuItem.setAccelerator(KeyStroke.getKeyStroke(
        KeyEvent.VK_S, Toolkit.getDefaultToolkit()
        .getMenuShortcutKeyMask(), true));
exportMenuItem
.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(
        final java.awt.event.ActionEvent e) {
        MainFrameEx.this.exportFile();
    }
    });

    openMenuItem.setText(Messages.getString("MathViewer.open"));
    fileMenu.add(openMenuItem);
    openMenuItem.setAccelerator(KeyStroke.getKeyStroke(
        KeyEvent.VK_O, Toolkit.getDefaultToolkit()
        .getMenuShortcutKeyMask(), true));
openMenuItem
.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(
        final java.awt.event.ActionEvent e) {
        MainFrameEx.this.openFile();
    }
    });

    jMenuBar.add(fileMenu);

    editMenu.setText(Messages.getString("MathViewer.EditMenu"));

    formattedCopyMenuItem.setText(Messages
        .getString("MathViewer.formattedCopy"));
    editMenu.add(formattedCopyMenuItem);
    formattedCopyMenuItem.setAccelerator(KeyStroke.getKeyStroke(
        KeyEvent.VK_C, Toolkit.getDefaultToolkit()
        .getMenuShortcutKeyMask()
        | InputEvent.SHIFT_DOWN_MASK, true));

formattedCopyMenuItem
.addActionListener(new ActionListener() {
    public void actionPerformed(final ActionEvent e) {
        MainFrameEx.this.copyToClipboard(true);
    }
    });

    pasteMenuItem.setText(Messages.getString("MathViewer.paste"));
    editMenu.add(pasteMenuItem);
    pasteMenuItem.setAccelerator(KeyStroke.getKeyStroke(
        KeyEvent.VK_V, Toolkit.getDefaultToolkit()
        .getMenuShortcutKeyMask(), true));

pasteMenuItem.addActionListener(new ActionListener() {
    public void actionPerformed(final ActionEvent e) {
        MainFrameEx.this.pasteFromClipboard();
    }
    });

    unformattedCopyMenuItem.setText(Messages
        .getString("MathViewer.unformattedCopy"));
    editMenu.add(unformattedCopyMenuItem);
    unformattedCopyMenuItem.setAccelerator(KeyStroke
        .getKeyStroke(KeyEvent.VK_C, Toolkit.getDefaultToolkit()
            .getMenuShortcutKeyMask(), true));

    unformattedCopyMenuItem
    .addActionListener(new ActionListener() {
        public void actionPerformed(final ActionEvent e) {
            MainFrameEx.this.copyToClipboard(false);
        }
    });

    jMenuBar.add(editMenu);

    viewMenu.setText(Messages.getString("MathViewer.viewMenu"));

    aliasMenuItem.setSelected(true);
    aliasMenuItem.setText(Messages.getString("MathViewer.alias"));
    viewMenu.add(aliasMenuItem);
    aliasMenuItem.setSelected((Boolean) LayoutContextImpl
        .getDefaultLayoutContext().getParameter(
            Parameter.ANTIALIAS));
    aliasMenuItem
    .addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(
            final java.awt.event.ItemEvent e) {
            MainFrameEx.this.getMathComponent()
            .setParameter(
                Parameter.ANTIALIAS,
                MainFrameEx.this.aliasMenuItem
                .isSelected());
        }
    });

    smallerMenuItem.setText(Messages
        .getString("MathViewer.textSmaller"));
    viewMenu.add(smallerMenuItem);
    smallerMenuItem.setAccelerator(KeyStroke.getKeyStroke(
        /*KeyEvent.VK_SUBTRACT, Toolkit.getDefaultToolkit()
        .getMenuShortcutKeyMask(), true));*/
KeyEvent.VK_MINUS, Toolkit.getDefaultToolkit()
.getMenuShortcutKeyMask(), true));

smallerMenuItem
.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(
        final java.awt.event.ActionEvent e) {
        final JMathComponent jmc = MainFrameEx.this
        .getMathComponent();
        jmc.setFontSize(jmc.getFontSize()
            / MainFrameEx.FONT_SIZE_MULTIPLICATOR);
    }
    });

    biggerMenuItem.setText(Messages
        .getString("MathViewer.textBigger"));
    viewMenu.add(biggerMenuItem);
    biggerMenuItem.setAccelerator(KeyStroke.getKeyStroke(
        /*KeyEvent.VK_ADD, Toolkit.getDefaultToolkit()
        .getMenuShortcutKeyMask(), true));*/
KeyEvent.VK_PLUS, Toolkit.getDefaultToolkit()
.getMenuShortcutKeyMask(), true));
biggerMenuItem
.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(
        final java.awt.event.ActionEvent e) {
        final JMathComponent jmc = MainFrameEx.this
        .getMathComponent();
        jmc.setFontSize(jmc.getFontSize()
            * MainFrameEx.FONT_SIZE_MULTIPLICATOR);
    }
    });

    debugMenuItem.setSelected(true);
    debugMenuItem.setText(Messages.getString("MathViewer.debug"));
    viewMenu.add(debugMenuItem);
    debugMenuItem.setSelected((Boolean) LayoutContextImpl
        .getDefaultLayoutContext().getParameter(Parameter.DEBUG));
    debugMenuItem
    .addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(
            final java.awt.event.ItemEvent e) {
            MainFrameEx.this.getMathComponent()
            .setParameter(
                Parameter.DEBUG,
                MainFrameEx.this.debugMenuItem
                .isSelected());
        }
    });

    refreshMenuItem.setText(Messages
        .getString("MathViewer.textRefresh"));
    viewMenu.add(refreshMenuItem);
    refreshMenuItem.setAccelerator(KeyStroke.getKeyStroke(
        KeyEvent.VK_Y, Toolkit.getDefaultToolkit()
        .getMenuShortcutKeyMask(), true));
refreshMenuItem
.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(
        final java.awt.event.ActionEvent e) {
        MainFrameEx.this.updateFromTextArea();
    }
    });

    jMenuBar.add(viewMenu);

    helpMenu.setText(Messages.getString("MathViewer.helpMenu"));

    aboutMenuItem.setText(Messages
        .getString("MathViewer.aboutMenuItem"));
    helpMenu.add(aboutMenuItem);
    aboutMenuItem.addActionListener(new ActionListener() {
        public void actionPerformed(final ActionEvent e) {
            MainFrameEx.this.displayAbout();
        }
    });

    jMenuBar.add(helpMenu);

    setJMenuBar(jMenuBar);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertMacro(String text)
    {
        int pos = getXMLEditor().getCaretPosition();
        String s1 = getXMLEditor().getText().substring(0,pos);
        String s2 = getXMLEditor().getText().substring(pos);
        s1 += text + s2;
        getXMLEditor().setText(s1);
        updateFromTextArea();
    }
    private void refreshCMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshCMenuItemActionPerformed
        MainFrameEx.this.updateFromTextArea();
    }//GEN-LAST:event_refreshCMenuItemActionPerformed

    private void insertTableMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertTableMenuItemActionPerformed
        InsertTableDialog dlg = new InsertTableDialog(this, true);
        dlg.setVisible(true);

        if(dlg.getMathMLText() != null)
        {
            insertMacro(dlg.getMathMLText());
        }
    }//GEN-LAST:event_insertTableMenuItemActionPerformed

    private void orMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orMenuItemActionPerformed
        insertMacro("<apply><or/><ci>a</ci><ci>b</ci></apply>");
    }//GEN-LAST:event_orMenuItemActionPerformed

    private void andMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andMenuItemActionPerformed
        insertMacro("<apply><and/><ci>a</ci><ci>b</ci></apply>");
    }//GEN-LAST:event_andMenuItemActionPerformed

    private void notMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notMenuItemActionPerformed
        insertMacro("<apply><not/><ci>a</ci></apply>");
    }//GEN-LAST:event_notMenuItemActionPerformed

    private void alphaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alphaMenuItemActionPerformed
        insertMacro("<mi>&#x003b1;</mi>");
    }//GEN-LAST:event_alphaMenuItemActionPerformed

    private void betaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betaMenuItemActionPerformed
        insertMacro("<mi>&#x003b2;</mi>");
    }//GEN-LAST:event_betaMenuItemActionPerformed

    private void gammaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gammaMenuItemActionPerformed
        insertMacro("<mi>&#x003b3;</mi>");
    }//GEN-LAST:event_gammaMenuItemActionPerformed

    private void deltaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deltaMenuItemActionPerformed
        insertMacro("<mi>&#x003b4;</mi>");
    }//GEN-LAST:event_deltaMenuItemActionPerformed

    private void epsilonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epsilonMenuItemActionPerformed
        insertMacro("<mi>&#x003b5;</mi>");
    }//GEN-LAST:event_epsilonMenuItemActionPerformed

    private void zetaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zetaMenuItemActionPerformed
        insertMacro("<mi>&#x003b6;</mi>");
    }//GEN-LAST:event_zetaMenuItemActionPerformed

    private void omegaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_omegaMenuItemActionPerformed
        insertMacro("<mi>&#x003c9;</mi>");
    }//GEN-LAST:event_omegaMenuItemActionPerformed

    private void insertPolynomMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertPolynomMenuItemActionPerformed
        InsertPolynomDialog dlg = new InsertPolynomDialog(this, true);
        dlg.setVisible(true);

        if(dlg.getMathMLText() != null)
        {
            insertMacro(dlg.getMathMLText());
        }
    }//GEN-LAST:event_insertPolynomMenuItemActionPerformed


    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameEx().setVisible(true);
            }
        });
    }*/

    public void displayAbout() {
        final JDialog aDialog = MainFrameEx.this.getAboutDialog();
        aDialog.pack();
        final Point loc = MainFrameEx.this.getLocation();
        loc
                .translate(
                        (MainFrameEx.this.getWidth() - aDialog.getWidth()) / 2,
                        0);
        aDialog.setLocation(loc);
        aDialog.setVisible(true);

    }

    private JDialog getAboutDialog() {
        if (this.aboutDialog == null) {
            this.aboutDialog = new AboutDialog(this);
        }
        return this.aboutDialog;
    }

    public JMathComponent getMathComponent() {
        if (this.mathComponent == null) {
            this.mathComponent = new JMathComponent();
            this.mathComponent
                    .setContent("<math><mtext>" //$NON-NLS-1$
                            + Messages.getString("MathViewer.noFileLoaded") + "</mtext></math>"); //$NON-NLS-1$ //$NON-NLS-2$
            this.mathComponent.setFocusable(true);
        }
        return this.mathComponent;
    }

    protected void exportFile() {
        MainFrameEx.FILEIO.saveDocument(this, this.getMathComponent()
                .getDocument(), this.getMathComponent().getParameters());
    }

    protected void openFile() {
        final File file = MainFrameEx.FILEIO.selectFileToOpen(this);
        this.loadFile(file);
    }

    public void loadFile(final File f) {
        final Document doc = MainFrameEx.FILEIO.loadFile(this, f);
        if (doc != null) {
            this.getMathComponent().setDocument(doc);
            this.getXMLEditor().setText(
                    MathMLSerializer.serializeDocument(doc, false, false));
        }

    }
    
    private XMLTextEditor getXMLEditor() {
        if (this.xmlEditor == null) {
            this.xmlEditor = new XMLTextEditor();
            this.xmlEditor.setEditorKit(new XMLEditorKit(new XMLContext()));
            /*this.xmlEditor.setText("<?xml version='1.0'?>\n"
                    + "<math xmlns='http://www.w3.org/1998/Math/MathML'>\n"
                    + "</math>");*/
            this.xmlEditor.setText("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                    //DOCTYPE for W3C compliance obviously not supported
                    //+ "<!DOCTYPE math PUBLIC -//W3C//DTD MathML 2.0//EN' "
                    //+ "'http://www.w3.org/Math/DTD/mathml2/mathml2.dtd'>\n"
                    + "<math xmlns='http://www.w3.org/1998/Math/MathML'>\n"
                    //+ "<mrow>\n"
                    + "<mi>a</mi>\n"
                    + /*"<msup><mi>x</mi><mn>2</mn></msup>\n"
                    + "<mo>+</mo><mi>b</mi>\n"
                    + "<mi>x</mi><mo>+</mo><mi>c</mi>\n"
                    + "<mo>=</mo><mo>0</mo>\n"
                    + "</mrow>\n"
                    + */"</math>");

            this.xmlEditor.setEditable(true);
            this.xmlEditor.setComponentPopupMenu(contextMenu);
            this.xmlEditor.getDocument().addDocumentListener(
                    new DocumentListener() {
                        public void changedUpdate(
                                final DocumentEvent documentevent) {
                            MainFrameEx.this.updateFromTextArea(documentevent);
                        }

                        public void insertUpdate(
                                final DocumentEvent documentevent) {
                            MainFrameEx.this.updateFromTextArea(documentevent);
                        }

                        public void removeUpdate(
                                final DocumentEvent documentevent) {
                            MainFrameEx.this.updateFromTextArea(documentevent);
                        }
                    });
            this.xmlEditor.setBackground(Color.WHITE);
        }
        return this.xmlEditor;
    }

    private void updateFromTextArea() {

        try {
            this.getMathComponent().setContent(this.getXMLEditor().getText());
            this.xmlEditor.setBackground(Color.getHSBColor(0.3f, 0.2f, 1.0f));
            // CHECKSTYLE:OFF
            // in this case, we want to explicitly provide catch-all error
            // handling.
        } catch (final RuntimeException e) {
            // CHECKSTYLE:ON
            this.xmlEditor.setBackground(Color.getHSBColor(0f, 0.2f, 1.0f));
        }
    }

    private void updateFromTextArea(DocumentEvent documentevent) {
        long start, end;

        start = System.nanoTime();

        try {
            this.getMathComponent().setContent(documentevent, this.getXMLEditor().getText());
            this.xmlEditor.setBackground(Color.getHSBColor(0.3f, 0.2f, 1.0f));
            // CHECKSTYLE:OFF
            // in this case, we want to explicitly provide catch-all error
            // handling.
        } catch (final RuntimeException e) {
            // CHECKSTYLE:ON
            e.printStackTrace();
            this.xmlEditor.setBackground(Color.getHSBColor(0f, 0.2f, 1.0f));
        }

        end = System.nanoTime();

        LOGGER.info(" --- draw="+(end-start)/1000000d+"[ms]");
    }

    
    public void displaySettings() {
        new ParametersDialog(MainFrameEx.this).setVisible(true);
        MainFrameEx.this.debugMenuItem
                .setSelected(((Boolean) MainFrameEx.this.mathComponent
                        .getParameters().getParameter(Parameter.DEBUG))
                        .booleanValue());
        MainFrameEx.this.aliasMenuItem
                .setSelected(((Boolean) MainFrameEx.this.mathComponent
                        .getParameters().getParameter(Parameter.ANTIALIAS))
                        .booleanValue());

    }

        private void pasteFromClipboard() {
        final Transferable content = Toolkit.getDefaultToolkit()
                .getSystemClipboard().getContents(null);
        if (content != null
                && content.isDataFlavorSupported(DataFlavor.stringFlavor)) {
            try {
                final String newContent = (String) content
                        .getTransferData(DataFlavor.stringFlavor);
                this.getXMLEditor().setText(newContent);
                // CHECKSTYLE:OFF
                // in this case, we want to explicitly provide catch-all error
                // handling.
            } catch (final Exception e) {
                // CHECKSTYLE:ON
                JOptionPane.showMessageDialog(this, new String[] {
                        Messages.getString("MathViewer.pasteFailure"),
                        e.toString(), }, Messages
                        .getString("MathViewer.error"),
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void copyToClipboard(final boolean formatted) {
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(
                new StringSelection(MathMLSerializer.serializeDocument(
                        this.mathComponent.getDocument(), false, formatted)),
                null);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JCheckBoxMenuItem aliasMenuItem;
    private javax.swing.JMenuItem alphaMenuItem;
    private javax.swing.JMenuItem andMenuItem;
    private javax.swing.JMenuItem betaMenuItem;
    private javax.swing.JMenuItem biggerMenuItem;
    private javax.swing.JMenu combinatoricsMenu;
    private javax.swing.JPopupMenu contextMenu;
    private javax.swing.JCheckBoxMenuItem debugMenuItem;
    private javax.swing.JMenuItem deltaMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem epsilonMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exportMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem formattedCopyMenuItem;
    private javax.swing.JMenuItem gammaMenuItem;
    private javax.swing.JMenu greekMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu insertMenu;
    private javax.swing.JMenuItem insertPolynomMenuItem;
    private javax.swing.JMenuItem insertTableMenuItem;
    private javax.swing.JPanel jContentPane;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu logicsMenu;
    private javax.swing.JMenuItem notMenuItem;
    private javax.swing.JMenuItem omegaMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem orMenuItem;
    private javax.swing.JMenuItem overMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem refreshCMenuItem;
    private javax.swing.JMenuItem refreshMenuItem;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JScrollPane scrollPane2;
    private javax.swing.JMenuItem smallerMenuItem;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JMenuItem unformattedCopyMenuItem;
    private javax.swing.JMenu viewMenu;
    private javax.swing.JMenuItem zetaMenuItem;
    // End of variables declaration//GEN-END:variables

}
